[package]
name = "stat-api"
version = "0.2.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
actix-web = "4.10.2"
chrono = { version = "0.4.40", default-features = false, features = ["serde", "std"] }
dotenv = "0.15"
sea-orm = { version = "1.1.7", features = ["debug-print", "runtime-tokio", "sqlx-sqlite", "with-uuid"] }
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.16.0", features = ["v4"] }
thiserror = "2.0.12"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
utoipa = { version = "5.3.1", features = ["chrono", "uuid"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"] }
regex = "1.11.1"
actix-governor = { version = "0.8.0", features = ["log", "logger"] }
actix-multipart = "0.7.2"
actix-files = "0.6.6"
mime = "0.3.17"
validator = { version = "0.20.0", features = ["derive"] }
actix-cors = "0.7.1"

[dev-dependencies]
rstest = "0.25.0"
tokio = { version = "1.44.1", features = ["rt", "macros"] }
rand = "0.9.0"
migration = { path = "migration" }
