[package]
name = "stat-api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration"]

[dependencies]
actix-web = "4.9.0"
chrono = { version = "0.4.39", default-features = false, features = ["serde", "std"] }
log = "0.4.25"
dotenv = "0.15"
sea-orm = { version = "1.1.4", features = ["debug-print", "runtime-tokio", "sqlx-sqlite", "with-uuid"] }
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.12.0", features = ["v4"] }
thiserror = "2.0.11"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
utoipa = { version = "5.3.1", features = ["chrono", "uuid"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"] }
regex = "1.11.1"
utoipauto = "0.2.0"
itertools = "0.14.0"

[dev-dependencies]
rstest = "0.24.0"
migration = { path = "migration" } # depends on your needs
