[package]
name = "stat-api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
entity = { path = "entity" }
#migration = { path = "migration" } # depends on your needs
actix-web = "4.9.0"
chrono = { version = "0.4.39", default-features = false, features = ["clock", "serde", "std"] }
log = "0.4.22"
dotenv = "0.15"
sea-orm = { version = "1.1.3", features = ["debug-print", "runtime-tokio", "runtime-tokio-rustls", "sqlx-postgres", "sqlx-sqlite", "with-uuid"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
uuid = { version = "1.11.0", features = ["v4"] }
thiserror = "2.0.9"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
utoipa = { version = "5.3.1", features = ["chrono", "uuid"] }
utoipa-swagger-ui = { version = "8.1.1", features = ["actix-web"] }
regex = "1.11.1"
actix-extensible-rate-limit = "0.4.0"
utoipauto = "0.2.0"
