services:
  server:
    environment:
      DATABASE_URL: sqlite:///app/static/app.db
      FILES_PATH: /app/static
#      ALLOWED_HOST: '["http://localhost:3000"]'
      ALLOWED_METHODS: '["GET","PUT","POST"]'
      ADMIN_KEY: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      HOST: 0.0.0.0
      PORT: 8080
    image: ghcr.io/sidecuter/statapi-rs:latest
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static
