//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "goal")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_right_goal::Entity")]
    RoleRightGoal,
}

impl Related<super::role_right_goal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleRightGoal.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

