//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod aud;
pub mod change_plan;
pub mod goal;
pub mod plan;
pub mod problem;
pub mod review;
pub mod right;
pub mod role;
pub mod role_right_goal;
pub mod select_aud;
pub mod site_stat;
pub mod start_way;
pub mod user;
pub mod user_id;
pub mod user_role;

