//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "review")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Uuid,
    pub creation_date: DateTime,
    pub text: String,
    pub image_name: Option<String>,
    pub problem_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::problem::Entity",
        from = "Column::ProblemId",
        to = "super::problem::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Problem,
    #[sea_orm(
        belongs_to = "super::user_id::Entity",
        from = "Column::UserId",
        to = "super::user_id::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserId,
}

impl Related<super::problem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problem.def()
    }
}

impl Related<super::user_id::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserId.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
