//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role_right_goal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub right_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub goal_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::goal::Entity",
        from = "Column::GoalId",
        to = "super::goal::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Goal,
    #[sea_orm(
        belongs_to = "super::right::Entity",
        from = "Column::RightId",
        to = "super::right::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Right,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::RoleId",
        to = "super::role::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Role,
}

impl Related<super::goal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Goal.def()
    }
}

impl Related<super::right::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Right.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
