//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::select_aud::Entity")]
    SelectAud,
}

impl Related<super::select_aud::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SelectAud.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
