//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "start_way")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Uuid,
    pub start_id: String,
    pub end_id: String,
    pub visit_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::aud::Entity",
        from = "Column::EndId",
        to = "super::aud::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Aud2,
    #[sea_orm(
        belongs_to = "super::aud::Entity",
        from = "Column::StartId",
        to = "super::aud::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Aud1,
    #[sea_orm(
        belongs_to = "super::user_id::Entity",
        from = "Column::UserId",
        to = "super::user_id::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserId,
}

impl Related<super::user_id::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserId.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
